from django.db import models
from django.utils import timezone


class Document(models.Model):
    """
    Model to store documents for RAG retrieval.
    """
    title = models.CharField(max_length=255, db_index=True)
    full_text = models.TextField()
    date = models.DateTimeField(default=timezone.now, db_index=True)
    tags = models.CharField(max_length=500, blank=True, help_text="Comma-separated tags")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date']
        verbose_name = 'Document'
        verbose_name_plural = 'Documents'

    def __str__(self):
        return self.title

    def get_tags_list(self):
        """Return tags as a list."""
        return [tag.strip() for tag in self.tags.split(',') if tag.strip()]


class QA_Record(models.Model):
    """
    Model to store question-answer pairs generated by the RAG system.
    """
    question = models.TextField()
    answer = models.TextField(blank=True)
    retrieved_documents = models.ManyToManyField(
        Document,
        related_name='qa_records',
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'QA Record'
        verbose_name_plural = 'QA Records'

    def __str__(self):
        return f"Q: {self.question[:50]}..."
